[database]
host = 192.168.1.201
port = 3306
user = root
password = a12345
database_jp = stock_dataset
database_kr = stock_dataset

[default]
output_dir = D:\\stock\\StockSearcher
start_date = 2020-01-01
end_date = 2099-12-31
period = 5


; [default]
; output_dir = D:\\stock\\stockdatajp
; period = 1

; [database]
; host = 192.168.0.200
; port = 3306
; user = nowonbun
; password = a12345
; database = stock_prediction_jp

; [machine]
; learn_start_date = 2013-01-01
; learn_end_date = 2024-03-05
; sequence_length = 240
; predict_days = 1
; weight = 2.2
; weight2 = 2.5
; machine_name = machine1
; modelType = model1

; [learn]
; epochs = 5
; count = 5
; cut_rate = 1.0
; weight = 500
; beta_1=0.9
; beta_2=0.999
; skip_number = -1
; end_date = 2024-03-01

; [search]
; machine_download = 
