//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stocksearcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class stockdata
    {
        public string code { get; set; }
        public long timestamp { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<long> open_price { get; set; }
        public Nullable<long> high_price { get; set; }
        public Nullable<long> low_price { get; set; }
        public Nullable<long> closed_price { get; set; }
        public Nullable<long> volume_price { get; set; }
        public Nullable<bool> isuse { get; set; }
    
        public virtual stocklist stocklist { get; set; }
    }
}
