//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 템플릿에서 생성되었습니다.
//
//     이 파일을 수동으로 변경하면 응용 프로그램에서 예기치 않은 동작이 발생할 수 있습니다.
//     이 파일을 수동으로 변경하면 코드가 다시 생성될 때 변경 내용을 덮어씁니다.
// </auto-generated>
//------------------------------------------------------------------------------

namespace stocksearcher
{
    using System;
    using System.Collections.Generic;
    
    public partial class stocklist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public stocklist()
        {
            this.stockdata = new HashSet<stockdata>();
        }
    
        public string code { get; set; }
        public string date { get; set; }
        public string name { get; set; }
        public Nullable<int> stockcode { get; set; }
        public string type33code { get; set; }
        public string type17code { get; set; }
        public string typescalecode { get; set; }
        public Nullable<bool> isuse { get; set; }
    
        public virtual stocktype stocktype { get; set; }
        public virtual type17 type17 { get; set; }
        public virtual type33 type33 { get; set; }
        public virtual typescale typescale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<stockdata> stockdata { get; set; }
    }
}
